twist_mux:
  ros__parameters:
  #Esto es un multiplexor para usar el joy, nav 2 y todos vallan a con¿md-vel
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100